apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: namespaceconfigs.example.com
spec:
  group: example.com
  names:
    kind: NamespaceConfig
    listKind: NamespaceConfigList
    plural: namespaceconfigs
    singular: namespaceconfig
  scope: Cluster
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              properties:
                labels:
                  type: object
                  additionalProperties:
                    type: string
      subresources:
        status: {}
